# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
cache: packages
bioc_packages:
  - edgeR
  - IHW
  - limma
  - qvalue
  - RNASeqPower
  - sva
  - zFPKM
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov(quiet = FALSE)'
latex: false

